language: objective-c
osx_image: xcode7.2
script:
  - set -o pipefail
  - xcodebuild test -scheme MappingJSON -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
  - xcodebuild test -scheme MappingJSON-Mac -configuration Release | xcpretty -c
  - xcodebuild test -scheme MappingJSON-tvOS -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c
  - xcodebuild build -scheme MappingJSON-watchOS -configuration Release -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" | xcpretty -c
